version: '3'
services:
  stream_vault_addon:
    container_name: stream_vault_addon
    build: .
    environment:
      - NODE_ENV=prod
    ports:
      - '1337:1337'
    networks:
      - stream_network

networks:
  stream_network:
    external: true
